#版本号，请勿修改
version: 1

#高级世界设置
#生物设置
organism:
  #每个宇宙最大生物数量,-1为不限制
  max: -1
  #生物限制类型
  #ban为封禁以下生物，allow为只允许以下生物生成，auto自动跟随服务端
  type: "auto"
  list:
    - PIG
    - COW
#红石设置
redStone:
  #是否限制高频红石
  LimitHighFrequency: false
  #在一秒内红石信号更改多少次判定为高频
  frequency: 300